import type { AdminPermission } from "./admin-permissions";
import { STAFF_ACCESS_OPTIONS } from "./admin-staff-input";

function escape(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }

export function buildStaffInvitationEmail(input: { recipientName: string; actionLink: string; requiresPassword: boolean; permissions: AdminPermission[] }) {
  const areas = STAFF_ACCESS_OPTIONS.filter((option) => input.permissions.includes(option.value)).map((option) => option.label);
  const button = input.requiresPassword ? "Set up your team account" : "Sign in to HelloCara";
  const intro = input.requiresPassword ? "Create a password, then secure your sign-in with an authenticator app." : "Sign in using your existing password, then complete the security check. Your password has not changed.";
  return {
    subject: "You’re invited to the HelloCara team",
    text: `Hello ${input.recipientName},\n\nYou’ve been invited to the HelloCara admin workspace.\n\n${intro}\n\nYour access: ${areas.join(", ")}.\n\n${button}: ${input.actionLink}\n\n${input.requiresPassword ? "This personal link can only be used once. If it has expired, ask your workspace owner to resend your invitation.\n\n" : ""}If you weren’t expecting this invitation, you can ignore it or contact support@hellocara.ie.\n\nThe HelloCara team`,
    html: `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Join your HelloCara team</title></head><body style="margin:0;background:#f3f6f4;font-family:Arial,Helvetica,sans-serif;color:#20392c"><div style="display:none;max-height:0;overflow:hidden">Your team workspace is ready. Secure your account and get started.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:40px 20px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;margin:auto"><tr><td style="padding:0 0 24px;font-size:24px;font-weight:700;letter-spacing:-1px">HelloCara<span style="display:block;margin-top:7px;font-size:11px;font-weight:400;letter-spacing:2px;color:#617367">TEAM WORKSPACE</span></td></tr><tr><td style="padding:36px 28px;border:1px solid #dce5df;border-radius:16px;background:#fff"><p style="margin:0 0 16px;color:#617367;font-size:14px">Hello ${escape(input.recipientName)},</p><h1 style="margin:0 0 18px;font-size:29px;line-height:1.25;letter-spacing:-1px">You’re part of the team.</h1><p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#52685c">You’ve been invited to the HelloCara admin workspace. ${escape(intro)}</p><div style="margin:24px 0;padding:18px;border:1px solid #dce5df;border-radius:10px;background:#f6f8f6"><p style="margin:0 0 8px;font-size:11px;font-weight:700;letter-spacing:1.5px;color:#617367">YOUR ACCESS</p><p style="margin:0;font-size:14px;line-height:1.7">${areas.map(escape).join(" · ")}</p></div><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="border-radius:8px;background:#294c37"><a href="${escape(input.actionLink)}" style="display:block;padding:17px 20px;color:#fff;font-size:14px;font-weight:700;text-decoration:none">${button} →</a></td></tr></table><p style="margin:20px 0 0;font-size:12px;line-height:1.7;color:#617367">${input.requiresPassword ? "This personal link can only be used once. If it has expired, ask your workspace owner for a fresh invitation." : "Use the email address this invitation was sent to. Your existing password remains the same."}</p></td></tr><tr><td style="padding:24px 4px;font-size:12px;line-height:1.7;color:#617367">Not expecting this? You can ignore this invitation or contact <a style="color:#294c37" href="mailto:support@hellocara.ie">support@hellocara.ie</a>.<br>HelloCara · Cliste Systems Limited</td></tr></table></td></tr></table></body></html>`,
  };
}
