import type { Metadata } from "next";
import { LockKeyhole, ShieldCheck, Users } from "lucide-react";
import { ClisteLogoMark } from "@/components/cliste-logo-mark";
import { StaffPasswordForm } from "./password-form";
import { requireStaffPasswordSetup } from "./session";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Join your team — HelloCara" };

export default async function StaffSetupPage() {
  const { staff } = await requireStaffPasswordSetup();
  return <main className="min-h-dvh bg-[#f3f6f4] px-5 py-8 sm:px-8 sm:py-12"><div className="mx-auto max-w-5xl"><header className="mb-10 flex items-center gap-2.5"><ClisteLogoMark size={32} priority /><span className="text-xl font-semibold tracking-tight text-[#20392c]">HelloCara</span></header><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:gap-16"><aside className="pt-3"><span className="inline-flex items-center gap-2 rounded-full border border-[#d8e3dc] bg-white px-3 py-1.5 text-xs font-medium text-[#476550]"><Users className="size-3.5" />Your team workspace</span><h1 className="mt-5 text-4xl font-semibold leading-tight tracking-[-.035em] text-[#20392c]">Great work starts<br />with a great team.</h1><p className="mt-4 max-w-sm text-sm leading-7 text-[#617367]">Welcome{staff.display_name ? `, ${staff.display_name}` : ""}. Secure your account to join the HelloCara admin workspace.</p><ol aria-label="Team setup progress" className="mt-7 space-y-4">{["Create your password", "Set up two-factor authentication", "Open your workspace"].map((label, index) => <li key={label} aria-current={index === 0 ? "step" : undefined} className="flex items-center gap-3 text-sm"><span className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs ${index === 0 ? "bg-[#294c37] text-white" : "border border-[#d5dfd8] text-[#849187]"}`}>{index + 1}</span><span className={index === 0 ? "font-semibold text-[#20392c]" : "text-[#617367]"}>{label}</span></li>)}</ol><p className="mt-8 flex max-w-sm items-start gap-2 text-xs leading-6 text-[#617367]"><ShieldCheck className="mt-1 size-4 shrink-0" />Your owner has chosen the areas you can access. You can only see and manage those areas.</p></aside><section aria-labelledby="staff-setup-title" className="rounded-2xl border border-[#dce5df] bg-white p-6 shadow-[0_12px_45px_-25px_rgba(30,64,45,.3)] sm:p-8"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#617a68]">Step 1 of 2</p><h2 id="staff-setup-title" className="mt-3 text-2xl font-semibold tracking-tight text-[#20392c]">Make your account yours</h2><p className="mt-3 text-sm leading-6 text-[#617367]">Choose a password that only you know.</p><div className="mt-7"><StaffPasswordForm email={staff.email} /></div></section></div><footer className="mt-10 flex flex-wrap items-center justify-between gap-3 border-t border-[#dbe5de] pt-5 text-xs text-[#617367]"><span>HelloCara · Cliste Systems Limited</span><span className="flex items-center gap-1.5"><LockKeyhole className="size-3" />Secure team setup</span></footer></div></main>;
}
